name: Run 2.x tests
on:
  push:
    branches:
      - '2.x'
      - '2.x-**'

jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Create docker-compose.yml
        run: curl https://raw.githubusercontent.com/farmOS/farmOS/2.x/docker/docker-compose.development.yml -o docker-compose.yml
      - name: Start containers
        run: docker-compose up -d && sleep 5
      - name: Install farmOS
        run: docker-compose exec -u www-data -T www drush site-install -y --db-url=pgsql://farm:farm@db/farm --account-pass=admin
      - name: Run npm install
        run: npm install
      - name: Run tests
        run: node node_modules/mocha/bin/mocha --recursive

